# Generated by Django 5.0.3 on 2024-05-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_tiki_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
