# Generated by Django 5.0.3 on 2024-05-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_is_sale_remove_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
