# Generated by Django 5.0.3 on 2024-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_profile_state_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tiki_product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
