# Generated by Django 5.0.3 on 2024-05-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_alter_shippingaddress_shipping_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_zipcode',
        ),
    ]
